/**
 * This file is automatically generated by the mvr SDK.
 * You can edit this file, but it will be overwritten on the next run.
 * You should check this file in your version control system.
 *
 * Run this script before building your project to ensure that the mvr.ts file stays up to date.
 *
 * You can use this pre-built cache when initializing your "NamedPackagesPlugin" by calling
 * `getMvrCache("mainnet")` or `getMvrCache("testnet")`
 */

const mainnetResolution = {
  packages: {
  },
  types: {
  },
};
const testnetResolution = {
  packages: {
    // '@mysten-soleng/coin-flip': '0xa486b1b5c5566722aa930af6af7bcf3ec49486887a5d4b6540215611b69b5066',
  },
  types: {},
};

export function getMvrCache(network: "mainnet" | "testnet") {
  return network === "mainnet" ? mainnetResolution : testnetResolution;
}
