# https://docs.docker.com/compose/compose-file/compose-file-v3/

services:
  satoshi_api:
    build: .
    expose:
      - 8080
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
    env_file:
      - .env.local

